crepe_model: full
device: cuda
fmax: 550
fmin: 50
freqcut: 10
ft_sr: 50
generator_ckpt: /data/cheoljun/hifigan_ckpts/generator_ep2w_hifigan_libritts_eng.ckpt
generator_configs:
  bias: true
  channels: 512
  in_channels: 14
  kernel_size: 7
  nonlinear_activation: LeakyReLU
  nonlinear_activation_params:
    negative_slope: 0.1
  out_channels: 1
  resblock_dilations:
  - - 1
    - 3
    - 5
  - - 1
    - 3
    - 5
  - - 1
    - 3
    - 5
  resblock_kernel_sizes:
  - 3
  - 7
  - 11
  spk_emb_size: 64
  upsample_kernel_sizes:
  - 16
  - 10
  - 8
  - 4
  upsample_scales:
  - 8
  - 5
  - 4
  - 2
  use_additional_convs: true
  use_weight_norm: true
linear_model_path: /home/cheoljun/GuBERT/linearmodels/wavlm_large-9_cut-10_mngu_linear.pkl
normalize: true
pitch_q: 1
speech_model: microsoft/wavlm-large
spk_emb_size: 64
spk_ft_ckpt: /data/cheoljun/hifigan_ckpts/spkfc_ep2w_hifigan_libritts_eng.ckpt
spk_ft_size: 1024
sr: 16000
target_layer: 9
pitch_stats_method: htk
